### ISSUE TITLE
Incomplete execution instructions / error on running

### ISSUE THREAD

**Issue by alecjacobson** [tobiasisenberg/Motion-Plausibility-Profiles#1]
Hello,
I'm handling your submission for the reproducibility stamp. I've run into issues trying to run your code.

So far I have issued:

```bash
pip3 install geopy plotly matplotlib numpy powerlaw
python _inaturalist.py
```

I get the following error:

```
running Python 3.8.11 (default, Jul 29 2021, 14:57:32) 
[Clang 12.0.0 ]
Traceback (most recent call last):
  File "_inaturalist.py", line 8, in <module>
    os.chdir(pathOfTheScript)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

The readme mentions something about csv files but I don't see any included in the repository and the instructions are not clear to me how to retrieve them. Could you please correct any misunderstandings I've made and/or improve the readme instructions?

**Comment by tobiasisenberg** [comment]
Hi Alec,

Indeed, the script needs additional data. Apparently the readme was not clear enough. I updated it and now include a data requirements section. I cannot include the data as part of the repository because the data is owned by iNaturalist. Please follow the instructions to download the data from iNaturalist as described in the updated readme.

The error you are getting, however, does not have anything to do with this missing data. Line 8 is supposed to ```cd``` into the directory of the script. This works fine on Windows 10. Which OS are you using? Maybe this is somehow OS-dependent.

Cheers,

Tobias

**Comment by tobiasisenberg** [comment]
I also now adjusted the script to not attempt the ```cd``` in line 8 if the ```pathOfTheScript``` variable is empty, so please pull and try again. Still, if you let me know your OS I can investigate further.

**Comment by alecjacobson** [comment]
Thanks. I tried that and am getting a new error. If I run

    python _inaturalist.py droseraceae.csv

then I get

```
File "_inaturalist.py", line 231
    print("No genus name for id: " + str(newEntry["id"]), end='')
                                                             ^
SyntaxError: invalid syntax
````

**Comment by tobiasisenberg** [comment]
Hi Alec,

The ```_inaturalist.py``` script does not take arguments, as instructed by the GRSI webpage ("The script should run without parameters"). So the argument with the data file is ignored. But it seems that you are trying to run the script without all the data files present, which would have led to further errors, so I now added a check before the loading of the files to ignore those that do not exist. So it should now run with just one data file present (but it will generate incomplete results). But I still encourage you to get the data files for all mentioned plant families to see the appropriate visual results.

Second, you apparently have two versions of Python installed, one 2.x and one 3.x. The call of ```python``` only calls the 2.x version, which led to the error you describe because the print statement does not have the end parameter in Python 2. This script, however, needs Python 3.x, so please call:
```
python3 _inaturalist.py
```
I also added a check that should give you an appropriate warning if you call it with Python 2. Hope this helps. Please update again.

**Comment by tobiasisenberg** [comment]
Alec, did you manage to make some progress or are there any other issues?

**Comment by alecjacobson** [comment]
I'm still trying to find the time to download all the data. inaturalist only seems to allow exporting one at a time and takes a while for each one. So it's been difficult to carve out time to do this in one sitting :-( 

Is it possible to use the license information to create your own (sub)set of data that you could host rather than rely on manually preparing this export on inaturalist?

**Comment by tobiasisenberg** [comment]
I had sent you a PM to ask if I should share the current data with you. Just let me know if I should do that. But I really do not want to share the data here due to the protection status of the plants (iNaturalist may decide to protect more observations in the future).

**Comment by alecjacobson** [comment]
Thanks, Tobias. I'm checking with the chair of the replicability stamp to undestand how we treat this with respect to replicability. It's a bit tricky if the data itself might disappear/change/change process.

**Comment by alecjacobson** [comment]
Thanks for the data. Now I can run and see this:

```
[lots of lines like this one:]
No genus name for id: 113753293 ; scientific name: Lentibulariaceae
Read 103200 iNaturalist entries that include location data and are not captive plants.
Out of these, 29514 entries obscured.
And 73686 entries unobscured.
With 6297 entries with genus information only, this is 6.1%.
With 89427 entries with research grade data, this is 86.7%.
With 1112 out of 104311 entries with private data (incl. private entries w/o location data), this is 1.1%.

In total, 192 out of 806 taxa are (partially!) obscured.

Generating visualization
Collecting information about people's posts counts (incl. sorting, may take a bit)
Species visualizations
Traceback (most recent call last):
  File "_inaturalist.py", line 782, in <module>
    pio.write_image(fig, 'vis/0_iNaturalist-species-count-alphabetical.pdf')
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/plotly/io/_kaleido.py", line 267, in write_image
    img_data = to_image(
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/plotly/io/_kaleido.py", line 133, in to_image
    raise ValueError(
ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido
```

I'll try installing `kaleido` and running again.

**Comment by tobiasisenberg** [comment]
Thanks a lot for the update. The first part along the lines of ```No genus name for id``` is normal. These are entries where people only entered the family name, not the full scientific name. These I have to treat differently for the visualization (explained in the paper).
The second part about the rendering engine, thanks a lot for pointing this out and sorry for the oversight. I thought this was installed automatically along with plotly, but apparently it is not. It is needed for PDF export. I will update the readme. Please note to use
```
pip3 install -U kaleido
```
to install it for your Python 3 installation.

**Comment by alecjacobson** [comment]
k thanks, now I got this error:

```
In total, 192 out of 806 taxa are (partially!) obscured.

Generating visualization
Collecting information about people's posts counts (incl. sorting, may take a bit)
Species visualizations
Traceback (most recent call last):
  File "_inaturalist.py", line 782, in <module>
    pio.write_image(fig, 'vis/0_iNaturalist-species-count-alphabetical.pdf')
  File "/Users/ajx/opt/miniconda3/lib/python3.8/site-packages/plotly/io/_kaleido.py", line 297, in write_image
    path.write_bytes(img_data)
  File "/Users/ajx/opt/miniconda3/lib/python3.8/pathlib.py", line 1241, in write_bytes
    with self.open(mode='wb') as f:
  File "/Users/ajx/opt/miniconda3/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Users/ajx/opt/miniconda3/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'vis/0_iNaturalist-species-count-alphabetical.pdf'
```
I'm trying
```
mkdir vis/
```
and running again.

**Comment by alecjacobson** [comment]
I think this line is a problem on macos:

       os.makedirs(pathOfTheScript + "\\vis", exist_ok=True)

it would work if it's 

       os.makedirs(pathOfTheScript + "/vis", exist_ok=True)
       
or maybe


       os.makedirs(pathOfTheScript + os.sep + "vis", exist_ok=True)
       
or

       os.makedirs(os.path.join(pathOfTheScript,"vis"), exist_ok=True)

**Comment by alecjacobson** [comment]
OK, feel free to fix the /vis directory issue, but otherwise it looks like everything runs well. I'm declaring success. Thanks for bearing with the long delays due to context switching. Glad we could get it to run in the end.

**Comment by tobiasisenberg** [comment]
Perfect, thanks a lot for all these comments. Also thanks a lot to you for bearing with me and helping me to fix these bugs and lacks of proper documentation. I now fixed the issue with the separator (there were a few more cases in the script), so now it should also run ok on MacOS and Linux. I am also very glad that we could improve things and that we now have a success.

I only have the question now how we continue from here. Will I be informed about the outcome somehow, will the journal be informed to mark the paper accordingly? Essentially, how do we go from here?

**Comment by tobiasisenberg** [comment]
Nevermind, just received an e-mail that the stamp was awarded. Thanks again!
